apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-conf-tyk-headless
  labels:
    app: apps-tyk-headless
    chart: tyk-headless-0.8.2
    release: tyk-headless
    heritage: Helm
data:
  api.song.json: |
    {
      "name": "Song API",
      "slug": "song-api",
      "api_id": "1",
      "org_id": "1"
      },
      "definition": {
        "location": "header",
        "key": "x-api-version"
      },
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default",
            "use_extended_paths": true
          }
        }
      },
      "proxy": {
        "listen_path": "/song/",
        "target_url": "http://podiyumm-song:80/",
        "strip_listen_path": true
      },
      "active": true
    }