apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-gateway-conf-{{ include "tyk-headless.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
#{{- if .Values.gateway.conf -}}
  tyk_mgmt.conf:
  {{ .Values.gateway.conf | toJson | quote }}
#{{- else -}}
#  {{- (.Files.Glob "configs/tyk_mgmt.conf").AsConfig | nindent 2 }}
#{{- end -}}